### ISSUE TITLE
single cell analysis 2020 file Access 

### ISSUE THREAD

**Issue by ShadenAlharbi** [dpcook/scrna_seq_workshop_2020#1]
Hello David

I couldn't get access through google drive for the matrix.mtx file from CellRanger.

May I get a copy, please?

**Comment by dpcook** [comment]
Hi @ShadenAlharbi,

Sorry that the link became inactive. I've re-uploaded it to another google drive here: https://drive.google.com/drive/folders/1MwXESXfiJBzssjlE2zfgytp19NMn-6Oe?usp=sharing

Alternatively, feel free to try out any of the public data offered from 10x Genomics: https://www.10xgenomics.com/resources/datasets
